# Generated by Django 4.2.7 on 2023-11-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
